import type { City } from "@/lib/cities";

export type ZoningIndexRow = { zone_code: string; zone_name: string };

// GENERATED FILE — do not hand-edit.
// Run: node scripts/export-zoning-index.mjs --limit-per-city 200
export const ZoningIndexByCity: Record<City, ZoningIndexRow[]> = {
  seattle: [
    { zone_code: `C1-125`, zone_name: `Commercial 1` },
    { zone_code: `C1-160`, zone_name: `Commercial 1` },
    { zone_code: `C1-30`, zone_name: `Commercial 1` },
    { zone_code: `C1-40`, zone_name: `Commercial 1` },
    { zone_code: `C1-40 (0.75)`, zone_name: `Commercial 1 Incentive` },
    { zone_code: `C1-65`, zone_name: `Commercial 1` },
    { zone_code: `C1-85`, zone_name: `Commercial 1` },
    { zone_code: `C1P-30`, zone_name: `Commercial 1` },
    { zone_code: `C1P-40`, zone_name: `Commercial 1` },
    { zone_code: `C2-30`, zone_name: `Commercial 2` },
    { zone_code: `C2-40`, zone_name: `Commercial 2` },
    { zone_code: `C2-65`, zone_name: `Commercial 2` },
    { zone_code: `C2P-40`, zone_name: `Commercial 2` },
    { zone_code: `DH1/45`, zone_name: `Downtown Harborfront 1` },
    { zone_code: `DH2/55`, zone_name: `Downtown Harborfront 2` },
    { zone_code: `DH2/65`, zone_name: `Downtown Harborfront 2` },
    { zone_code: `DH2/85`, zone_name: `Downtown Harborfront 2` },
    { zone_code: `DMC-125`, zone_name: `Downtown Mixed Commercial` },
    { zone_code: `DMC-160`, zone_name: `Downtown Mixed Commercial` },
    { zone_code: `DMC 240/290-400`, zone_name: `Downtown Mixed Commercial` },
    { zone_code: `DMC 340/290-400`, zone_name: `Downtown Mixed Commercial` },
    { zone_code: `DMC-65`, zone_name: `Downtown Mixed Commercial` },
    { zone_code: `DMC-85`, zone_name: `Downtown Mixed Commercial` },
    { zone_code: `DMC 85/65-150`, zone_name: `Downtown Mixed Commercial` },
    { zone_code: `DMR/C 125/65`, zone_name: `Downtown Mixed Residential/Residential` },
    { zone_code: `DMR/C 240/125`, zone_name: `Downtown Mixed Residential/Residential` },
    { zone_code: `DMR/C 65/65-150`, zone_name: `Downtown Mixed Residential/Residential` },
    { zone_code: `DMR/C 65/65-85`, zone_name: `Downtown Mixed Residential/Residential` },
    { zone_code: `DMR/C 85/65`, zone_name: `Downtown Mixed Residential/Residential` },
    { zone_code: `DMR/R 125/65`, zone_name: `Downtown Mixed Residential/Residential` },
    { zone_code: `DMR/R 240/65`, zone_name: `Downtown Mixed Residential/Residential` },
    { zone_code: `DMR/R 85/65`, zone_name: `Downtown Mixed Residential/Residential` },
    { zone_code: `DOC1 U/450/U`, zone_name: `Downtown Office Core 1` },
    { zone_code: `DOC2 500/300-500`, zone_name: `Downtown Office Core 2` },
    { zone_code: `DRC 85-150`, zone_name: `Downtown Retail Core` },
    { zone_code: `HR`, zone_name: `Highrise` },
    { zone_code: `HR-PUD`, zone_name: `Highrise` },
    { zone_code: `IB U/30`, zone_name: `Industrial Buffer` },
    { zone_code: `IB U/45`, zone_name: `Industrial Buffer` },
    { zone_code: `IB U/65`, zone_name: `Industrial Buffer` },
    { zone_code: `IB U/85`, zone_name: `Industrial Buffer` },
    { zone_code: `IC-45`, zone_name: `Industrial Commercial` },
    { zone_code: `IC-65`, zone_name: `Industrial Commercial` },
    { zone_code: `IC-85`, zone_name: `Industrial Commercial` },
    { zone_code: `IC 85-160`, zone_name: `Industrial Commercial` },
    { zone_code: `IDM 150/85-150`, zone_name: `International District Mixed` },
    { zone_code: `IDM-65-150`, zone_name: `International District Mixed` },
    { zone_code: `IDM-75-85`, zone_name: `International District Mixed` },
    { zone_code: `IDM 75/85-150`, zone_name: `International District Mixed` },
    { zone_code: `IDR 150`, zone_name: `International District Residential` },
    { zone_code: `IDR 45/125-240`, zone_name: `International District Residential` },
    { zone_code: `IDR/C 125/150-240`, zone_name: `International District Residential` },
    { zone_code: `IG1 U/45`, zone_name: `General Industrial 1` },
    { zone_code: `IG1 U/65`, zone_name: `General Industrial 1` },
    { zone_code: `IG1 U/85`, zone_name: `General Industrial 1` },
    { zone_code: `IG2 U/45`, zone_name: `General Industrial 2` },
    { zone_code: `IG2 U/65`, zone_name: `General Industrial 2` },
    { zone_code: `IG2 U/85`, zone_name: `General Industrial 2` },
    { zone_code: `LR1`, zone_name: `Lowrise 1` },
    { zone_code: `LR1 RC`, zone_name: `Lowrise 1` },
    { zone_code: `LR2`, zone_name: `Lowrise 2` },
    { zone_code: `LR2 (0.75)`, zone_name: `Lowrise 2 Incentive` },
    { zone_code: `LR2 PUD`, zone_name: `Lowrise 2` },
    { zone_code: `LR2 RC`, zone_name: `Lowrise 2` },
    { zone_code: `LR3`, zone_name: `Lowrise 3` },
    { zone_code: `LR3 (0.75)`, zone_name: `Lowrise 3 Incentive` },
    { zone_code: `LR3 (1.2)`, zone_name: `Lowrise 3 Incentive` },
    { zone_code: `LR3 PUD`, zone_name: `Lowrise 3` },
    { zone_code: `LR3 RC`, zone_name: `Lowrise 3` },
    { zone_code: `MIO-105-C1-65`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-105-C2-65`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-105-LR2`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-105-LR3`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-105-MR`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-105-NC2-40`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-105-NC2P-40`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-105-NC3-40`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-105-NC3-65`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-105-NC3-85`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-105-NC3P-40`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-105-NC3P-65`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-107-LR1`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-107-MR`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-160/125-LR3`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-160/125-SF 5000`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-160/140-LR3`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-160/140-SF 5000`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-160-HR`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-160-MR`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-160-NC3-160`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-160-NC3-85`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-160-NC3P-85`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-200-HR`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-240-HR`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-240-HR-PUD`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-240-MR`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-240-NC3P-160`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-37-C2-40`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-37-IC-45`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-37-IG1-U/45`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-37-LR1`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-37-LR2`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-37-LR3`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-37-LR3 RC`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-37-NC1-40`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-37-NC2-40`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-37-SF 5000`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-50-C1-40`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-50-LR1`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-50-LR1 RC`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-50-LR2`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-50-LR3`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-50-NC1-40`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-50-NC2-40`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-50-SF 5000`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-65-C1-40`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-65-C1-65`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-65-IC-45`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-65-LR2`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-65-LR3`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-65-MR`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-65-NC2-40`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-65-NC2P-40`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-65-NC2P-65`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-65-NC3-65`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-65-NC3-85`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-65-NC3P-65`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-65-SF 5000`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-70-HR`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-70-MR`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-70-NC3-85`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-70-NC3P-160`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-70-SF 5000`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-90-HR`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-90-NC3-85`, zone_name: `Major Institution Overlay` },
    { zone_code: `MIO-90-SF 5000`, zone_name: `Major Institution Overlay` },
    { zone_code: `MPC-YT`, zone_name: `Master Planned Community` },
    { zone_code: `MR`, zone_name: `Midrise 1` },
    { zone_code: `MR (0.75)`, zone_name: `Midrise Incentive` },
    { zone_code: `MR (1.2)`, zone_name: `Midrise Incentive` },
    { zone_code: `MR (1.3)`, zone_name: `Midrise Incentive` },
    { zone_code: `MR (2.0)`, zone_name: `Midrise Incentive` },
    { zone_code: `MR-85`, zone_name: `Midrise 1` },
    { zone_code: `MR-RC`, zone_name: `Midrise` },
    { zone_code: `NC1-30`, zone_name: `Neighborhood Commercial 1` },
    { zone_code: `NC1-40`, zone_name: `Neighborhood Commercial 1` },
    { zone_code: `NC1-65`, zone_name: `Neighborhood Commercial 1` },
    { zone_code: `NC1P-30`, zone_name: `Neighborhood Commercial 1` },
    { zone_code: `NC1P-40`, zone_name: `Neighborhood Commercial 1` },
    { zone_code: `NC1P-40 (0.75)`, zone_name: `Neighborhood Commercial 1 Incentive` },
    { zone_code: `NC1P-40 (1.2)`, zone_name: `Neighborhood Commercial 1 Incentive` },
    { zone_code: `NC2-30`, zone_name: `Neighborhood Commercial 2` },
    { zone_code: `NC2-40`, zone_name: `Neighborhood Commercial 2` },
    { zone_code: `NC2-40 (1.3)`, zone_name: `Neighborhood Commercial 2 Incentive` },
    { zone_code: `NC2-65`, zone_name: `Neighborhood Commercial 2` },
    { zone_code: `NC2-65 (1.3)`, zone_name: `Neighborhood Commercial 2 Incentive` },
    { zone_code: `NC2-65 (3.0)`, zone_name: `Neighborhood Commercial 2 Incentive` },
    { zone_code: `NC2-65 (4.0)`, zone_name: `Neighborhood Commercial 2 Incentive` },
    { zone_code: `NC2P-30`, zone_name: `Neighborhood Commercial 2` },
    { zone_code: `NC2P-40`, zone_name: `Neighborhood Commercial 2` },
    { zone_code: `NC2P-40 (0.75)`, zone_name: `Neighborhood Commercial 2 Incentive` },
    { zone_code: `NC2P-40 (1.2)`, zone_name: `Neighborhood Commercial 2 Incentive` },
    { zone_code: `NC2P-65`, zone_name: `Neighborhood Commercial 2` },
    { zone_code: `NC2P-65 (0.75)`, zone_name: `Neighborhood Commercial 2 Incentive` },
    { zone_code: `NC2P-65 (1.3)`, zone_name: `Neighborhood Commercial 2 Incentive` },
    { zone_code: `NC2P-65 (3.0)`, zone_name: `Neighborhood Commercial 2 Incentive` },
    { zone_code: `NC2P-65 (4.0)`, zone_name: `Neighborhood Commercial 2 Incentive` },
    { zone_code: `NC3-125`, zone_name: `Neighborhood Commercial 3` },
    { zone_code: `NC3-160`, zone_name: `Neighborhood Commercial 3` },
    { zone_code: `NC3-30`, zone_name: `Neighborhood Commercial 3` },
    { zone_code: `NC3-40`, zone_name: `Neighborhood Commercial 3` },
    { zone_code: `NC3-65`, zone_name: `Neighborhood Commercial 3` },
    { zone_code: `NC3-65 (1.3)`, zone_name: `Neighborhood Commercial 3 Incentive` },
    { zone_code: `NC3-65 (2.0)`, zone_name: `Neighborhood Commercial 3 Incentive` },
    { zone_code: `NC3-65 (3.0)`, zone_name: `Neighborhood Commercial 3 Incentive` },
    { zone_code: `NC3-65 (4.0)`, zone_name: `Neighborhood Commercial 3 Incentive` },
    { zone_code: `NC3-85`, zone_name: `Neighborhood Commercial 3` },
    { zone_code: `NC3-85 (4.75)`, zone_name: `Neighborhood Commercial 3 Incentive` },
    { zone_code: `NC3P-160`, zone_name: `Neighborhood Commercial 3` },
    { zone_code: `NC3P-40`, zone_name: `Neighborhood Commercial 3` },
    { zone_code: `NC3P-65`, zone_name: `Neighborhood Commercial 3` },
    { zone_code: `NC3P-65 (1.3)`, zone_name: `Neighborhood Commercial 3 Incentive` },
    { zone_code: `NC3P-65 (2.0)`, zone_name: `Neighborhood Commercial 3 Incentive` },
    { zone_code: `NC3P-65 (3.0)`, zone_name: `Neighborhood Commercial 3 Incentive` },
    { zone_code: `NC3P-65 (4.0)`, zone_name: `Neighborhood Commercial 3 Incentive` },
    { zone_code: `NC3P-85`, zone_name: `Neighborhood Commercial 3` },
    { zone_code: `NC3P-85 (1.3)`, zone_name: `Neighborhood Commercial 3 Incentive` },
    { zone_code: `NC3P-85 (2.0)`, zone_name: `Neighborhood Commercial 3 Incentive` },
    { zone_code: `NC3P-85 (4.75)`, zone_name: `Neighborhood Commercial 3 Incentive` },
    { zone_code: `NC3P-85 (5.75)`, zone_name: `Neighborhood Commercial 3 Incentive` },
    { zone_code: `PMM-85`, zone_name: `Pike Market Mixed` },
    { zone_code: `PSM-100`, zone_name: `Pioneer Square Mixed` },
    { zone_code: `PSM 100/100-120`, zone_name: `Pioneer Square Mixed` },
    { zone_code: `PSM 100/100-130`, zone_name: `Pioneer Square Mixed` },
    { zone_code: `PSM 100/120-150`, zone_name: `Pioneer Square Mixed` },
    { zone_code: `PSM-245`, zone_name: `Pioneer Square Mixed` },
    { zone_code: `PSM-85-120`, zone_name: `Pioneer Square Mixed` },
    { zone_code: `RSL/TC`, zone_name: `Residential Small Lot` },
    { zone_code: `SF 5000`, zone_name: `Residential Single Family 5000` },
    { zone_code: `SF 5000-PUD`, zone_name: `Residential Single Family 5000` },
  ],
  austin: [
    { zone_code: `AG`, zone_name: `AG` },
    { zone_code: `AG-NP`, zone_name: `AG` },
    { zone_code: `AV`, zone_name: `AV` },
    { zone_code: `CBD`, zone_name: `CBD` },
    { zone_code: `CBD-CO`, zone_name: `CBD` },
    { zone_code: `CBD-CURE`, zone_name: `CBD` },
    { zone_code: `CBD-CURE-CO`, zone_name: `CBD` },
    { zone_code: `CBD-ETOD-DBETOD`, zone_name: `CBD` },
    { zone_code: `CBD-H`, zone_name: `CBD` },
    { zone_code: `CBD-H-CURE`, zone_name: `CBD` },
    { zone_code: `CBD-H-ETOD-DBETOD`, zone_name: `CBD` },
    { zone_code: `CH`, zone_name: `CH` },
    { zone_code: `CH-CO`, zone_name: `CH` },
    { zone_code: `CH-CO-NP`, zone_name: `CH` },
    { zone_code: `CH-NP`, zone_name: `CH` },
    { zone_code: `CH-PDA`, zone_name: `CH` },
    { zone_code: `CH-PDA-NP`, zone_name: `CH` },
    { zone_code: `CR`, zone_name: `CR` },
    { zone_code: `CR-CO`, zone_name: `CR` },
    { zone_code: `CS`, zone_name: `CS` },
    { zone_code: `CS-1`, zone_name: `MF` },
    { zone_code: `CS-1-CO`, zone_name: `CS` },
    { zone_code: `CS-1-CO-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-CO-MU-NP`, zone_name: `CS` },
    { zone_code: `CS-1-CO-NP`, zone_name: `GR` },
    { zone_code: `CS-1-ETOD-DBETOD`, zone_name: `CS` },
    { zone_code: `CS-1-H`, zone_name: `CS` },
    { zone_code: `CS-1-H-NCCD-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-H-NCCD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-MU-CO`, zone_name: `CS` },
    { zone_code: `CS-1-MU-CO-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-MU-CO-HD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-MU-CO-NP`, zone_name: `CS` },
    { zone_code: `CS-1-MU-H-NP`, zone_name: `CS` },
    { zone_code: `CS-1-MU-NCCD-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-MU-NCCD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-MU-NP`, zone_name: `CS` },
    { zone_code: `CS-1-MU-V-CO-DB90-NP`, zone_name: `CS` },
    { zone_code: `CS-1-MU-V-CO-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-MU-V-CO-NP`, zone_name: `CS` },
    { zone_code: `CS-1-MU-V-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-MU-V-NCCD-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-MU-V-NP`, zone_name: `CS` },
    { zone_code: `CS-1-NCCD-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-NCCD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-NP`, zone_name: `CS` },
    { zone_code: `CS-1-V`, zone_name: `CS` },
    { zone_code: `CS-1-V-CO`, zone_name: `CS` },
    { zone_code: `CS-1-V-CO-DB90`, zone_name: `CS` },
    { zone_code: `CS-1-V-CO-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-V-CO-NCCD-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-V-CO-NP`, zone_name: `CS` },
    { zone_code: `CS-1-V-ETOD-DBETOD`, zone_name: `CS` },
    { zone_code: `CS-1-V-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-V-H-CO-NCCD-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-V-MU-CO-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-V-NCCD-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-1-V-NP`, zone_name: `CS` },
    { zone_code: `CS-CO`, zone_name: `CS` },
    { zone_code: `CS-CO-DB90-NP`, zone_name: `CS` },
    { zone_code: `CS-CO-ETOD-DBETOD`, zone_name: `CS` },
    { zone_code: `CS-CO-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-CO-MU-H-NP`, zone_name: `CS` },
    { zone_code: `CS-CO-MU-NP`, zone_name: `CS` },
    { zone_code: `CS-CO-NCCD-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-CO-NP`, zone_name: `CS` },
    { zone_code: `CS-CO-V-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-CURE`, zone_name: `CS` },
    { zone_code: `CS-ETOD-DBETOD`, zone_name: `CS` },
    { zone_code: `CS-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-H`, zone_name: `CS` },
    { zone_code: `CS-H-CO-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-HD-NCCD-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-HD-NCCD-NP`, zone_name: `CS` },
    { zone_code: `CS-H-HD-NCCD-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-H-MU-CO-NP`, zone_name: `CS` },
    { zone_code: `CS-H-MU-NCCD-NP`, zone_name: `CS` },
    { zone_code: `CS-H-NCCD-NP`, zone_name: `CS` },
    { zone_code: `CS-H-NP`, zone_name: `CS` },
    { zone_code: `CS-MU`, zone_name: `CS` },
    { zone_code: `CS-MU-CO`, zone_name: `CS` },
    { zone_code: `CS-MU-CO-DB90-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-CO-ETOD-DBETOD`, zone_name: `CS` },
    { zone_code: `CS-MU-CO-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-CO-HD-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-CO-H-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-CO-NCCD-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-CO-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-CO-NP/MF-6-CO-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-CO-V`, zone_name: `CS` },
    { zone_code: `CS-MU-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-H-CO-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-H-CO-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-H-NCCD-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-H-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-NCCD-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-NCCD-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-NP/MF-6-CO-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-V-CO`, zone_name: `CS` },
    { zone_code: `CS-MU-V-CO-DB90`, zone_name: `CS` },
    { zone_code: `CS-MU-V-CO-DB90-NP`, zone_name: `P` },
    { zone_code: `CS-MU-V-CO-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-V-CO-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-V-DB90-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-V-ETOD-DBETOD-DB90-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-V-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-V-NCCD-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-V-NCCD-NP`, zone_name: `CS` },
    { zone_code: `CS-MU-V-NP`, zone_name: `CS` },
    { zone_code: `CS-NCCD-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-NCCD-NP`, zone_name: `CS` },
    { zone_code: `CS-NP`, zone_name: `CS` },
    { zone_code: `CS-V`, zone_name: `CS` },
    { zone_code: `CS-V-CO`, zone_name: `CS` },
    { zone_code: `CS-V-CO-DB90`, zone_name: `CS` },
    { zone_code: `CS-V-CO-DB90-NP`, zone_name: `CS` },
    { zone_code: `CS-V-CO-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-V-CO-NP`, zone_name: `CS` },
    { zone_code: `CS-V-DB90`, zone_name: `CS` },
    { zone_code: `CS-V-DB90-NP`, zone_name: `CS` },
    { zone_code: `CS-V-ETOD-DBETOD`, zone_name: `CS` },
    { zone_code: `CS-V-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-V-MU-CO`, zone_name: `CS` },
    { zone_code: `CS-V-MU-NP`, zone_name: `CS` },
    { zone_code: `CS-V-NCCD-ETOD-DBETOD-NP`, zone_name: `CS` },
    { zone_code: `CS-V-NP`, zone_name: `CS` },
    { zone_code: `DMU`, zone_name: `DMU` },
    { zone_code: `DMU-CO`, zone_name: `DMU` },
    { zone_code: `DMU-CO-CURE`, zone_name: `DMU` },
    { zone_code: `DMU-CO-ETOD-DBETOD`, zone_name: `DMU` },
    { zone_code: `DMU-CURE`, zone_name: `DMU` },
    { zone_code: `DMU-CURE-CO`, zone_name: `DMU` },
    { zone_code: `DMU-CURE-CO-H`, zone_name: `DMU` },
    { zone_code: `DMU-ETOD-DBETOD`, zone_name: `DMU` },
    { zone_code: `DMU-H`, zone_name: `DMU` },
    { zone_code: `DMU-H-CO`, zone_name: `DMU` },
    { zone_code: `DMU-H-CO-ETOD-DBETOD`, zone_name: `DMU` },
    { zone_code: `DMU-H-ETOD-DBETOD`, zone_name: `DMU` },
    { zone_code: `DR`, zone_name: `DR` },
    { zone_code: `DR-CO`, zone_name: `DR` },
    { zone_code: `DR-H`, zone_name: `DR` },
    { zone_code: `DR-NP`, zone_name: `DR` },
    { zone_code: `ERC`, zone_name: `ERC` },
    { zone_code: `GO`, zone_name: `GO` },
    { zone_code: `GO-CO`, zone_name: `GO` },
    { zone_code: `GO-CO-ETOD-DBETOD-NP`, zone_name: `GO` },
    { zone_code: `GO-CO-MU-NP`, zone_name: `GO` },
    { zone_code: `GO-CO-NCCD-NP`, zone_name: `GO` },
    { zone_code: `GO-CO-NP`, zone_name: `GO` },
    { zone_code: `GO-ETOD-DBETOD`, zone_name: `GO` },
    { zone_code: `GO-ETOD-DBETOD-NP`, zone_name: `GO` },
    { zone_code: `GO-H`, zone_name: `GO` },
    { zone_code: `GO-H-CO-NCCD-NP`, zone_name: `GO` },
    { zone_code: `GO-H-CO-NP`, zone_name: `GO` },
    { zone_code: `GO-HD-NP`, zone_name: `GO` },
    { zone_code: `GO-H-ETOD-DBETOD`, zone_name: `GO` },
    { zone_code: `GO-H-NCCD-ETOD-DBETOD-NP`, zone_name: `GO` },
    { zone_code: `GO-H-NP`, zone_name: `GO` },
    { zone_code: `GO-MU`, zone_name: `GO` },
    { zone_code: `GO-MU-CO`, zone_name: `GO` },
    { zone_code: `GO-MU-CO-ETOD-DBETOD`, zone_name: `GO` },
    { zone_code: `GO-MU-CO-ETOD-DBETOD-NP`, zone_name: `GO` },
    { zone_code: `GO-MU-CO-NP`, zone_name: `GO` },
    { zone_code: `GO-MU-ETOD-DBETOD`, zone_name: `GO` },
    { zone_code: `GO-MU-H`, zone_name: `GO` },
    { zone_code: `GO-MU-H-CO-ETOD-DBETOD`, zone_name: `GO` },
    { zone_code: `GO-MU-H-CO-NP`, zone_name: `GO` },
    { zone_code: `GO-MU-H-ETOD-DBETOD`, zone_name: `GO` },
    { zone_code: `GO-MU-H-NP`, zone_name: `GO` },
    { zone_code: `GO-MU-NP`, zone_name: `LO` },
    { zone_code: `GO-MU-V-CO-NP`, zone_name: `GO` },
    { zone_code: `GO-MU-V-ETOD-DBETOD-NP`, zone_name: `GO` },
    { zone_code: `GO-MU-V-NP`, zone_name: `GO` },
    { zone_code: `GO-NCCD-ETOD-DBETOD-NP`, zone_name: `GO` },
    { zone_code: `GO-NCCD-NP`, zone_name: `GO` },
    { zone_code: `GO-NP`, zone_name: `GO` },
    { zone_code: `GO-V-CO`, zone_name: `GO` },
    { zone_code: `GO-V-CO-ETOD-DBETOD`, zone_name: `GO` },
    { zone_code: `GO-V-CO-NP`, zone_name: `GO` },
    { zone_code: `GO-V-ETOD-DBETOD`, zone_name: `GO` },
    { zone_code: `GO-V-ETOD-DBETOD-NP`, zone_name: `GO` },
    { zone_code: `GO-V-NP`, zone_name: `GO` },
    { zone_code: `GR`, zone_name: `GR` },
    { zone_code: `GR-CO`, zone_name: `GR-CO` },
    { zone_code: `GR-CO-DB90`, zone_name: `GR` },
    { zone_code: `GR-CO-ETOD-DBETOD`, zone_name: `GR` },
    { zone_code: `GR-CO-ETOD-DBETOD-NP`, zone_name: `GR` },
    { zone_code: `GR-CO-MU-HD-NP`, zone_name: `GR` },
    { zone_code: `GR-CO-MU-NP`, zone_name: `GR` },
    { zone_code: `GR-CO-NP`, zone_name: `GR` },
    { zone_code: `GR-DB90-NP`, zone_name: `GR` },
    { zone_code: `GR-ETOD-DBETOD`, zone_name: `GR` },
    { zone_code: `GR-ETOD-DBETOD-NP`, zone_name: `GR` },
    { zone_code: `GR-H`, zone_name: `GR` },
    { zone_code: `GR-H-CO-ETOD-DBETOD`, zone_name: `GR` },
    { zone_code: `GR-H-CO-MU-NP`, zone_name: `GR` },
    { zone_code: `GR-H-CO-NP`, zone_name: `GR` },
    { zone_code: `GR-HD-H-NCCD-ETOD-DBETOD-NP`, zone_name: `GR` },
    { zone_code: `GR-HD-NCCD-ETOD-DBETOD-NP`, zone_name: `GR` },
  ],
  chicago: [
    { zone_code: `B1-1`, zone_name: `4` },
    { zone_code: `B1-1.5`, zone_name: `1` },
    { zone_code: `B1-2`, zone_name: `1` },
    { zone_code: `B1-3`, zone_name: `1` },
    { zone_code: `B1-5`, zone_name: `1` },
    { zone_code: `B2-1`, zone_name: `1` },
    { zone_code: `B2-1.5`, zone_name: `4` },
    { zone_code: `B2-2`, zone_name: `4` },
    { zone_code: `B2-3`, zone_name: `2` },
    { zone_code: `B2-5`, zone_name: `4` },
    { zone_code: `B3-1`, zone_name: `5` },
    { zone_code: `B3-1.5`, zone_name: `1` },
    { zone_code: `B3-2`, zone_name: `4` },
    { zone_code: `B3-3`, zone_name: `4` },
    { zone_code: `B3-5`, zone_name: `1` },
    { zone_code: `C1-1`, zone_name: `2` },
    { zone_code: `C1-1.5`, zone_name: `2` },
    { zone_code: `C1-2`, zone_name: `4` },
    { zone_code: `C1-3`, zone_name: `2` },
    { zone_code: `C1-5`, zone_name: `2` },
    { zone_code: `C2-1`, zone_name: `2` },
    { zone_code: `C2-2`, zone_name: `2` },
    { zone_code: `C2-3`, zone_name: `2` },
    { zone_code: `C2-5`, zone_name: `2` },
    { zone_code: `C3-1`, zone_name: `2` },
    { zone_code: `C3-2`, zone_name: `2` },
    { zone_code: `C3-3`, zone_name: `2` },
    { zone_code: `C3-5`, zone_name: `2` },
    { zone_code: `DC-12`, zone_name: `8` },
    { zone_code: `DC-16`, zone_name: `8` },
    { zone_code: `DR-10`, zone_name: `9` },
    { zone_code: `DR-3`, zone_name: `9` },
    { zone_code: `DR-5`, zone_name: `9` },
    { zone_code: `DR-7`, zone_name: `9` },
    { zone_code: `DS-3`, zone_name: `10` },
    { zone_code: `DS-5`, zone_name: `10` },
    { zone_code: `DS-7`, zone_name: `10` },
    { zone_code: `DX-10`, zone_name: `7` },
    { zone_code: `DX-12`, zone_name: `7` },
    { zone_code: `DX-16`, zone_name: `7` },
    { zone_code: `DX-3`, zone_name: `7` },
    { zone_code: `DX-5`, zone_name: `7` },
    { zone_code: `DX-7`, zone_name: `7` },
    { zone_code: `M1-1`, zone_name: `3` },
    { zone_code: `M1-2`, zone_name: `3` },
    { zone_code: `M1-3`, zone_name: `3` },
    { zone_code: `M2-1`, zone_name: `3` },
    { zone_code: `M2-2`, zone_name: `3` },
    { zone_code: `M2-3`, zone_name: `3` },
    { zone_code: `M3-1`, zone_name: `3` },
    { zone_code: `M3-2`, zone_name: `3` },
    { zone_code: `M3-3`, zone_name: `3` },
    { zone_code: `PD`, zone_name: `5` },
    { zone_code: `PD 0`, zone_name: `5` },
    { zone_code: `PD 1`, zone_name: `5` },
    { zone_code: `PD 10`, zone_name: `5` },
    { zone_code: `PD 1000`, zone_name: `5` },
    { zone_code: `PD 1001`, zone_name: `5` },
    { zone_code: `PD 1002`, zone_name: `5` },
    { zone_code: `PD 1004`, zone_name: `5` },
    { zone_code: `PD 1005`, zone_name: `5` },
    { zone_code: `PD 1006`, zone_name: `5` },
    { zone_code: `PD 1007`, zone_name: `5` },
    { zone_code: `PD 1008`, zone_name: `5` },
    { zone_code: `PD 1009`, zone_name: `5` },
    { zone_code: `PD 1013`, zone_name: `5` },
    { zone_code: `PD 1014`, zone_name: `5` },
    { zone_code: `PD 1016`, zone_name: `5` },
    { zone_code: `PD 1017`, zone_name: `5` },
    { zone_code: `PD 1018`, zone_name: `5` },
    { zone_code: `PD 1019`, zone_name: `5` },
    { zone_code: `PD 102`, zone_name: `5` },
    { zone_code: `PD 1020`, zone_name: `5` },
    { zone_code: `PD 1021`, zone_name: `5` },
    { zone_code: `PD 1023`, zone_name: `5` },
    { zone_code: `PD 1024`, zone_name: `5` },
    { zone_code: `PD 1025`, zone_name: `5` },
    { zone_code: `PD 1027`, zone_name: `5` },
    { zone_code: `PD 1029`, zone_name: `5` },
    { zone_code: `PD 103`, zone_name: `5` },
    { zone_code: `PD 1030`, zone_name: `5` },
    { zone_code: `PD 1031`, zone_name: `5` },
    { zone_code: `PD 1032`, zone_name: `5` },
    { zone_code: `PD 1034`, zone_name: `5` },
    { zone_code: `PD 1035`, zone_name: `5` },
    { zone_code: `PD 1036`, zone_name: `5` },
    { zone_code: `PD 1037`, zone_name: `5` },
    { zone_code: `PD 1039`, zone_name: `5` },
    { zone_code: `PD 104`, zone_name: `5` },
    { zone_code: `PD 1040`, zone_name: `5` },
    { zone_code: `PD 1042`, zone_name: `5` },
    { zone_code: `PD 1043`, zone_name: `5` },
    { zone_code: `PD 1044`, zone_name: `5` },
    { zone_code: `PD 1046`, zone_name: `5` },
    { zone_code: `PD 1047`, zone_name: `5` },
    { zone_code: `PD 1048`, zone_name: `5` },
    { zone_code: `PD 1049`, zone_name: `5` },
    { zone_code: `PD 105`, zone_name: `5` },
    { zone_code: `PD 1050`, zone_name: `5` },
    { zone_code: `PD 1051`, zone_name: `5` },
    { zone_code: `PD 1052`, zone_name: `5` },
    { zone_code: `PD 1053`, zone_name: `5` },
    { zone_code: `PD 1054`, zone_name: `5` },
    { zone_code: `PD 1055`, zone_name: `5` },
    { zone_code: `PD 1057`, zone_name: `5` },
    { zone_code: `PD 1058`, zone_name: `5` },
    { zone_code: `PD 1059`, zone_name: `5` },
    { zone_code: `PD 106`, zone_name: `5` },
    { zone_code: `PD 1060`, zone_name: `5` },
    { zone_code: `PD 1062`, zone_name: `5` },
    { zone_code: `PD 1063`, zone_name: `5` },
    { zone_code: `PD 1064`, zone_name: `5` },
    { zone_code: `PD 1065`, zone_name: `5` },
    { zone_code: `PD 1066`, zone_name: `5` },
    { zone_code: `PD 1067`, zone_name: `5` },
    { zone_code: `PD 1068`, zone_name: `5` },
    { zone_code: `PD 1069`, zone_name: `5` },
    { zone_code: `PD 107`, zone_name: `5` },
    { zone_code: `PD 1071`, zone_name: `5` },
    { zone_code: `PD 1072`, zone_name: `5` },
    { zone_code: `PD 1075`, zone_name: `5` },
    { zone_code: `PD 1076`, zone_name: `5` },
    { zone_code: `PD 108`, zone_name: `5` },
    { zone_code: `PD 1080`, zone_name: `5` },
    { zone_code: `PD 1081`, zone_name: `5` },
    { zone_code: `PD 1084`, zone_name: `5` },
    { zone_code: `PD 1085`, zone_name: `5` },
    { zone_code: `PD 1086`, zone_name: `5` },
    { zone_code: `PD 1087`, zone_name: `5` },
    { zone_code: `PD 1088`, zone_name: `5` },
    { zone_code: `PD 1089`, zone_name: `5` },
    { zone_code: `PD 1090`, zone_name: `5` },
    { zone_code: `PD 1091`, zone_name: `5` },
    { zone_code: `PD 1092`, zone_name: `5` },
    { zone_code: `PD 1094`, zone_name: `5` },
    { zone_code: `PD 1095`, zone_name: `5` },
    { zone_code: `PD 1096`, zone_name: `5` },
    { zone_code: `PD 1097`, zone_name: `5` },
    { zone_code: `PD 1098`, zone_name: `5` },
    { zone_code: `PD 1099`, zone_name: `5` },
    { zone_code: `PD 11`, zone_name: `5` },
    { zone_code: `PD 110`, zone_name: `5` },
    { zone_code: `PD 1101`, zone_name: `5` },
    { zone_code: `PD 1102`, zone_name: `5` },
    { zone_code: `PD 1103`, zone_name: `5` },
    { zone_code: `PD 1104`, zone_name: `5` },
    { zone_code: `PD 1105`, zone_name: `5` },
    { zone_code: `PD 1107`, zone_name: `5` },
    { zone_code: `PD 1108`, zone_name: `5` },
    { zone_code: `PD 111`, zone_name: `5` },
    { zone_code: `PD 1110`, zone_name: `5` },
    { zone_code: `PD 1111`, zone_name: `5` },
    { zone_code: `PD 1113`, zone_name: `5` },
    { zone_code: `PD 1114`, zone_name: `5` },
    { zone_code: `PD 1115`, zone_name: `5` },
    { zone_code: `PD 1116`, zone_name: `5` },
    { zone_code: `PD 1117`, zone_name: `5` },
    { zone_code: `PD 1119`, zone_name: `5` },
    { zone_code: `PD 112`, zone_name: `5` },
    { zone_code: `PD 1120`, zone_name: `5` },
    { zone_code: `PD 1121`, zone_name: `5` },
    { zone_code: `PD 1124`, zone_name: `5` },
    { zone_code: `PD 1125`, zone_name: `5` },
    { zone_code: `PD 1126`, zone_name: `5` },
    { zone_code: `PD 1127`, zone_name: `5` },
    { zone_code: `PD 1129`, zone_name: `5` },
    { zone_code: `PD 113`, zone_name: `5` },
    { zone_code: `PD 1130`, zone_name: `5` },
    { zone_code: `PD 1131`, zone_name: `5` },
    { zone_code: `PD 1134`, zone_name: `5` },
    { zone_code: `PD 1135`, zone_name: `5` },
    { zone_code: `PD 1137`, zone_name: `5` },
    { zone_code: `PD 1138`, zone_name: `5` },
    { zone_code: `PD 114`, zone_name: `5` },
    { zone_code: `PD 1141`, zone_name: `5` },
    { zone_code: `PD 1142`, zone_name: `5` },
    { zone_code: `PD 1143`, zone_name: `5` },
    { zone_code: `PD 1144`, zone_name: `5` },
    { zone_code: `PD 1145`, zone_name: `5` },
    { zone_code: `PD 1146`, zone_name: `5` },
    { zone_code: `PD 1147`, zone_name: `5` },
    { zone_code: `PD 1148`, zone_name: `5` },
    { zone_code: `PD 1150`, zone_name: `5` },
    { zone_code: `PD 1151`, zone_name: `5` },
    { zone_code: `PD 1152`, zone_name: `5` },
    { zone_code: `PD 1153`, zone_name: `5` },
    { zone_code: `PD 1154`, zone_name: `5` },
    { zone_code: `PD 1155`, zone_name: `5` },
    { zone_code: `PD 1157`, zone_name: `5` },
    { zone_code: `PD 1158`, zone_name: `5` },
    { zone_code: `PD 1159`, zone_name: `5` },
    { zone_code: `PD 1160`, zone_name: `5` },
    { zone_code: `PD 1161`, zone_name: `5` },
    { zone_code: `PD 1164`, zone_name: `5` },
    { zone_code: `PD 1165`, zone_name: `5` },
    { zone_code: `PD 1166`, zone_name: `5` },
    { zone_code: `PD 1167`, zone_name: `5` },
    { zone_code: `PD 1168`, zone_name: `5` },
    { zone_code: `PD 1169`, zone_name: `5` },
    { zone_code: `PD 1171`, zone_name: `5` },
  ],
};
