#!/bin/bash
# Helper script to guide getting the correct Supabase connection string

PROJECT_REF="ugrbscrgztlqrptavsxp"
DASHBOARD_URL="https://supabase.com/dashboard/project/$PROJECT_REF/settings/database"

echo "🔗 Getting Supabase Connection String"
echo "======================================"
echo ""
echo "Follow these steps to get the correct connection string:"
echo ""
echo "1. Open your Supabase dashboard:"
echo "   $DASHBOARD_URL"
echo ""
echo "2. Click the 'Connect' button (top of the page)"
echo ""
echo "3. You'll see multiple connection options:"
echo ""
echo "   📌 For Serverless/Netlify (RECOMMENDED):"
echo "      → Select 'Connection pooling' tab"
echo "      → Choose 'Transaction mode' (port 6543)"
echo "      → Copy the connection string"
echo "      → Format: postgres://postgres:[PASSWORD]@db.$PROJECT_REF.supabase.co:6543/postgres"
echo ""
echo "   📌 For Persistent Backends:"
echo "      → Select 'Connection pooling' tab"
echo "      → Choose 'Session mode' (port 5432)"
echo "      → Copy the connection string"
echo ""
echo "   📌 For Direct Connection (IPv6 required):"
echo "      → Select 'URI' tab"
echo "      → Copy the connection string"
echo "      → Format: postgresql://postgres:[PASSWORD]@db.$PROJECT_REF.supabase.co:5432/postgres"
echo ""
echo "4. Once you have the connection string:"
echo ""
echo "   a) Update backend/db/.env:"
echo "      SUPABASE_DATABASE_URL=\"your-connection-string-here\""
echo ""
echo "   b) If password has special characters, URL-encode them:"
echo "      ? → %3F"
echo "      % → %25"
echo "      @ → %40"
echo "      # → %23"
echo ""
echo "   c) Test the connection:"
echo "      ./scripts/test-supabase-connection.sh"
echo ""
echo "   d) Run migrations:"
echo "      ./scripts/setup-supabase.sh"
echo ""
echo "=========================================="
echo ""
echo "💡 Tip: For Netlify deployment, use Transaction mode (port 6543)"
echo "   It's optimized for serverless functions and handles connection limits better."
